apiVersion: v1
kind: ConfigMap
metadata:
  name: db-configmap
  namespace: {{ .Values.adaptor.namespace }}
  labels:
    {{- include "adaptor.labels" . | nindent 4 }}
data:
  {{- with .Values.database }}
  HALO_DB_NAME: {{ required "A database name is required" .databaseName | quote }}
  HALO_DB_HOST: {{ required "A database hostname is required" .host | quote }}
  HALO_DB_USER: {{ required "A database user is required" .user | quote }}
  HALO_DB_PORT: {{ required "A database port is required" .port | quote }}
  {{- end }}
---  
