apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.adaptor.name }}
  namespace: {{ .Values.adaptor.namespace }}
  labels:
    app: {{ .Values.adaptor.name }}
    {{- include "adaptor.labels" . | nindent 4 }}
spec:
  ports:
  - name: http
    port: {{ .Values.adaptor.service.listeningPort }}
    targetPort: {{ .Values.adaptor.service.targetPort }}
    protocol: TCP
  type: LoadBalancer
  selector:
    app: {{ .Values.adaptor.name }}
---