apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.adaptor.namespace }}-attestation-secret
  namespace: {{ .Values.adaptor.namespace }}
  labels:
    {{- include "adaptor.labels" . | nindent 4 }}
type: Opaque
data:
  {{- with .Values.attestation }}
  apiKey: {{ required "attestation.apiKey is required" .apiKey | b64enc }}
  {{- end }}
---  