{{- if (.Values.aws).secretAccessKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.adaptor.namespace }}-aws-secret
  namespace: {{ .Values.adaptor.namespace }}
  labels:
    {{- include "adaptor.labels" . | nindent 4 }}
type: Opaque
data:
  {{- with .Values.aws }}
  secretAccessKey: {{ .secretAccessKey | b64enc }}
  sessionToken: {{ .sessionToken | b64enc }}
  {{- end }}
---  
{{- end }}