{{- if .Values.aws }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.adaptor.namespace }}-aws-secret
  namespace: {{ .Values.adaptor.namespace }}
  labels:
    {{- include "adaptor.labels" . | nindent 4 }}
type: Opaque
data:
  {{- with .Values.aws }}
  secretAccessKey: {{ .secretAccessKey | required "Require secret access key for AWS" | b64enc }}
  {{- end }}
---  
{{- end }}
