apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.adaptor.namespace }}-database-secret
  namespace: {{ .Values.adaptor.namespace }}
  labels:
    {{- include "adaptor.labels" . | nindent 4 }}
type: Opaque
data:
  {{- with .Values.database }}
  password: {{ required "database.password is required" .password | b64enc }}
  {{- end }}
---  