apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.adaptor.namespace }}-db-secret
  namespace: {{ .Values.adaptor.namespace }}
  labels:
    {{- include "adaptor.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.database.password | required "A database password is required" | b64enc }}
---  
