{{- if .Values.hsmService.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.adaptor.namespace }}-hsmservice-secret
  namespace: {{ .Values.adaptor.namespace }}
  labels:
    {{- include "hsmService.labels" . | nindent 4 }}
type: Opaque
data:
  rkiKey: {{ .Values.hsmService.rkiKey | required "The BDK used for RKI (hsmService.rkiKey) must be set" | b64enc }}
  destinationPinKey: {{ .Values.hsmService.destinationPinKey | required "The destination PIN key (hsmService.destinationPinKey) must be set" | b64enc }}
  destinationDataKey: {{ .Values.hsmService.destinationDataKey | quote | b64enc }}

  {{- if .Values.hsmService.tls.enabled }}
  serverTlsKey: {{ .Values.hsmService.tls.key | required "TLS key required if TLS enabled" | b64enc }}
  {{- end }}

  {{- if .Values.hsmService.hsm.enableMTls }}
  hsmTlsKey: {{ .Values.hsmService.hsm.key | required "HSM mTLS client key required if mTLS enabled" | b64enc }}
  {{- end }}

---  
{{- end }}
