apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.adaptor.namespace }}-redis-secret
  namespace: {{ .Values.adaptor.namespace }}
  labels:
    {{- include "adaptor.labels" . | nindent 4 }}
type: Opaque
data:
  {{- with .Values.redis }}
  password: {{ required "redis.password is required" .password | b64enc }}
  username: {{ .user }}
  {{- end }}
---  