apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.adaptor.namespace }}-redis-secret
  namespace: {{ .Values.adaptor.namespace }}
  labels:
    {{- include "adaptor.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.redis.password | b64enc }}
---
