{{- if .Values.redis.tls.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.adaptor.name }}-redis-tls-secret
  namespace: {{ .Values.adaptor.namespace }}
  labels:
    {{- include "adaptor.labels" . | nindent 4 }}
type: Opaque
data:
  {{- with .Values.redis.tls }}
  {{- if .key }}
  key.pem: {{ .key | b64enc }}
  {{- end }}
  {{- if .passphrase }}
  passphrase: {{ .passphrase | b64enc }}
  {{- end }}
  {{- end }}
---
{{- end }}
